import { LineEdit , HorizontalBox, Button , VerticalBox, ComboBox} from "std-widgets.slint";
export component MainWindow inherits Window {
    title: "Baze64 - Encode & Decode base64";
    min-width: 350px;
    min-height: 50px;

    callback encode_plaintext <=> plaintext.accepted;
    callback decode_base64 <=> base64.accepted;

    public function set_plaintext(text: string) {
        plaintext.text = text;
    }

    public function set_base64(text: string) {
        base64.text = text;
    }

    public function get_current_alphabet() -> string {
        return alphabet.current-value;
    }

    VerticalBox {
        HorizontalBox {
            plaintext := LineEdit {
                placeholder-text: "Plaintext";
            }
            base64 := LineEdit {
                placeholder-text: "Base64";
            }
        }
        alphabet := ComboBox { 
            model: ["standard", "urlsafe"];
            current-value: "standard";
         }
        Button {
            text: "Clear all";
            clicked => {
                plaintext.text = "";
                base64.text = "";
            }
        }
    }
}