[package]
name = "baze64"
description = "A base64 encoder & decoder"
version = "0.1.0"
edition = "2021"

[dependencies]
bitreader = "0.3.6"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
